# Generated by Django 4.2.3 on 2023-07-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tinyapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortenedurlstore",
            name="original_url",
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
