# Generated by Django 5.0.1 on 2024-01-16 06:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tinyapp", "0002_alter_shortenedurlstore_original_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("password", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "custom_user",
            },
        ),
    ]
